spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: practicastecnologicocomfenalco@gmail.com
    password: bxsizyvdizjyzcxs
    properties:
      mail:
       smtp:
        auth: true
        starttls:
          enable: true
          
  jackson:
    time-zone: America/Bogota
    
server:
  port: 9050  

